// iOS splash screen <link> tags. Generated by pwa-asset-generator from
// public/icons/icon-512x512.png against background #271310. Re-run via
// `npm run generate-splash` if the source icon changes.

const SPLASHES: { w: number; h: number; r: 2 | 3 }[] = [
  // iPad
  { w: 1024, h: 1366, r: 2 }, // 2048×2732
  { w: 834, h: 1194, r: 2 }, // 1668×2388
  { w: 768, h: 1024, r: 2 }, // 1536×2048
  { w: 820, h: 1180, r: 2 }, // 1640×2360
  { w: 834, h: 1112, r: 2 }, // 1668×2224
  { w: 810, h: 1080, r: 2 }, // 1620×2160
  { w: 744, h: 1133, r: 2 }, // 1488×2266
  // iPhone
  { w: 440, h: 956, r: 3 }, // 1320×2868 iPhone 16 Pro Max
  { w: 402, h: 874, r: 3 }, // 1206×2622 iPhone 16 Pro
  { w: 420, h: 912, r: 3 }, // 1260×2736 iPhone 16 Plus
  { w: 430, h: 932, r: 3 }, // 1290×2796 iPhone 15 Pro Max
  { w: 393, h: 852, r: 3 }, // 1179×2556 iPhone 14 Pro
  { w: 390, h: 844, r: 3 }, // 1170×2532 iPhone 14
  { w: 428, h: 926, r: 3 }, // 1284×2778 iPhone 14 Plus
  { w: 375, h: 812, r: 3 }, // 1125×2436 iPhone X / 11 Pro
  { w: 414, h: 896, r: 3 }, // 1242×2688 iPhone 11 Pro Max
  { w: 414, h: 896, r: 2 }, // 828×1792 iPhone 11 / XR
  { w: 414, h: 736, r: 3 }, // 1242×2208 iPhone Plus
  { w: 375, h: 667, r: 2 }, // 750×1334 iPhone 8 / SE
  { w: 320, h: 568, r: 2 }, // 640×1136 iPhone 5
]

export function AppleSplashScreens() {
  return (
    <>
      {SPLASHES.map(({ w, h, r }) => {
        const fileW = w * r
        const fileH = h * r
        return (
          <link
            key={`${fileW}-${fileH}`}
            rel="apple-touch-startup-image"
            href={`/icons/splash/apple-splash-${fileW}-${fileH}.png`}
            media={`(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${r}) and (orientation: portrait)`}
          />
        )
      })}
    </>
  )
}
